server:
  port: 8989
  context-path: /Cmfz
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    username: hr
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    encoding:
      charset: UTF-8
      force: true
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB


  profiles:
    active: test
mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*DaoMapper.xml
  type-aliases-package: com.baizhi.entity